# config/config.py

# MediaPipe
MEDIAPIPE_MAX_FACES = 1
MEDIAPIPE_MIN_DETECTION_CONFIDENCE = 0.5
MEDIAPIPE_MIN_TRACKING_CONFIDENCE = 0.5
MEDIAPIPE_REFINE_LANDMARKS = True

# Lipstick defaults
DEFAULT_OPACITY = 0.7
DEFAULT_GLOSS = 0.5
USE_HSV_BLENDING = True
